// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YukiChan.Server.Databases;

#nullable disable

namespace YukiChan.Server.Migrations.GuildsDb
{
    [DbContext(typeof(GuildsDbContext))]
    partial class GuildsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("YukiChan.Server.Models.GuildData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assignee");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("guild_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.HasKey("Id");

                    b.ToTable("guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
