// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YukiChan.Server.Databases;

#nullable disable

namespace YukiChan.Server.Migrations.CommandHistoryDb
{
    [DbContext(typeof(CommandHistoryDbContext))]
    [Migration("20230202160900_InitCommandHistoryDb")]
    partial class InitCommandHistoryDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("YukiChan.Server.Models.CommandHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assignee_id");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("channel_id");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command");

                    b.Property<string>("CommandText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_text");

                    b.Property<int>("Environment")
                        .HasColumnType("INTEGER")
                        .HasColumnName("environment");

                    b.Property<string>("GuildId")
                        .HasColumnType("TEXT")
                        .HasColumnName("guild_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("platform");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<int>("UserAuthority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_authority");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("command_history");
                });
#pragma warning restore 612, 618
        }
    }
}
